#
# Makefile for Phoenix-RTOS psdisk (Phoenix Systems Disk Tool)
#
# Copyright 2020 Phoenix Systems
#

NAME := psdisk
LOCAL_DIR := $(call my-dir)
SRCS := $(wildcard $(LOCAL_DIR)*.c)
LIBS := libptable

include $(binary.mk)
