#
# Makefile for Phoenix-RTOS hostutils common library
#
# Copyright 2021 Phoenix Systems
#

NAME := libhostutils-common
LOCAL_DIR := $(call my-dir)
SRCS := $(wildcard $(LOCAL_DIR)*.c)

include $(static-lib.mk)
