#
# Makefile for Phoenix-RTOS readmeterfs
#
# Copyright 2025 Phoenix Systems
#

NAME := readmeterfs
LOCAL_DIR := $(call my-dir)
SRCS := $(wildcard $(LOCAL_DIR)*.c)
LIBS := host-flash libmeterfs libphoenix libtinyaes

include $(binary.mk)
